### ISSUE TITLE
#

### ISSUE THREAD

**Issue by uszhen** [grimpenmire/one#1]
#support CDN

https://github.com/p4gefau1t/trojan-go

#Does not support CDN

https://github.com/trojan-gfw/trojan

**Comment by grimpenmire** [comment]
Thanks for the feedback. I know of trojan, but haven't personally tested it so far. Adding support for it to this project should be fairly straightforward, but I'm not sure I have the time to do it at the moment.

As to communicating issues through private channels, I don't agree with you. I believe discussing these things should be done in public. Any advantage gained through secrecy is fragile and unreliable. We should always go with the assumption that the censors know all that we know.

**Comment by uszhen** [comment]
That's the evil part of the GFW mechanism that you don't understand. It changes every day, not a fixed network blocking mechanism.
